algoritmo "Idade"
// Disciplina: Lopal ( Lógica de Programação)

//F9 (Executar código)


// Autor : Lorena Oliveira

// Data : 13/04/2026

var
 //Declaração de variaveis
 idade:real
 
inicio
// Seção de Comandos

   escreva ("coloque a idade:" )
   leia(idade)
   
   se idade>=18 entao
   
   escreval (" maior de idade, pode dirigir: ")
   
   senao
   escreval("menor de idade, não pode dirigir: ")
    fimse
fimalgoritmo
