algoritmo "Senha"
// Disciplina : Lopal ( Lógica de programação)

//F9 (excutar código)

// Autor : Lorena Oliveira
// Data : 14/04/2026

var
//Declaração de variavéis
senha: literal


inicio
// Seção de Comandos
   escreva ("coloque a senha:" )
   leia(senha)
   
   se senha="acb23" entao
   
   escreval ("senha correta")
   
   senao
   escreval("senha incorreta")
   fimse
   
fimalgoritmo
