algoritmo "Soma dos Números"

// Função: Lopal (Lógica de Programação)

//F9 ( executar o código)

//Autor:Lorena Oliveira
//Data: 13/04/2026
var
//Declaração Variáveis

numeroUm,numeroDOIS,numeroTRES,soma:real

inicio
// inicio dos dados

escreva ("coloque o primeiro valor: ")
leia (numeroUm)

escreva ("coloque o segundo valor: ")
leia (numeroDOIS)

escreva ("coloque o terceiro valor: ")
leia (numeroTRES)

//realizar a soma dos números
soma<- numeroUm + numeroDOIS + numeroTRES

escreval ("o valor final da soma", soma)

fimalgoritmo




