algoritmo "Voto"
// Disciplina : Lopal (Lógica de Programação)

//F9 (executyar código)

// Autor : Lorena Oliveira)
// Data : 14/04/2026

var
//Declaração de variavéis
idade:real


inicio
// Seção de Comandos 

   escreva(" digite a sua idade:" )
   leia(idade)
   
   se idade >=71 entao
   escreval("voto opcional")

   senao
        se idade >=18 entao
        escreval("voto obrigatório")
        
   senao
        se idade >=16 entao
        escreval("voto opcional")

    senao
        escreval ("Sua idade é", idade, " você não pode votar")
   
    fimse

fimalgoritmo
fimse
fimse
fimalgoritmo
